### ISSUE TITLE
The FHIR profiles fhir version change to 4.0.1

### ISSUE THREAD

**Issue by medcomire** [HL7/dk-core-r4#9]
The dk-core project in Simplifier has a 4.0.1 dependency but the  StructureDefinition xml fhir version is 4.0.0.  For now it will do but not forever :

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/28895413/78792793-de103d80-79b1-11ea-93e3-d7ab95ace358.png">

Yes, it is not the dk-core project but problem should be the same

**Comment by jkiddo** [comment]
Wrong repo
